### PR TITLE
Waltkthrough for JS-based apps

### PR DESCRIPTION
**Pull request by mderriey**
Associated with #14 

This is still a WIP, but I thought I'd share it with you.
I need to cover the session checks.

The associated code is [here](https://github.com/mderriey/idsrv-js-walkthrough/tree/dev) and the documentation is [there](http://mderriey.github.io/Documentation/docsv2/overview/jsGettingStarted.html)

I'll also review it since there must be typos and weird phrasing, but I'd like some general feedback, if it's what you thought about, and if things are missing/not the way you want them.

Cheers

### CODE REVIEW

**Comment by brockallen** [comment]
Looks good.

I had a bit of confusion I had at the beginning of part 1, so it might be helpful to let people know they will create 2 different projects in VS -- one for the JS and one for IdSvr.

Also, we probably should use the real oidc-token-manager.js from npm/bower. This also means I should fix up the sample to do the same -- I'll do that today.

Maybe just add a comment in the JS that the `display` is just a helper to format and show data to data to the user.

Other that that little feedback, it looks great -- thanks so much for doing this and helping out!

**Comment by mderriey** [comment]
I'm a bit confused regarding the check session feature.  

The spec says it's better than renewing the authorization request with `prompt=none` because it doesn't involve network traffic. To me, renewing the authorization request is also useful to renew the tokens, not just check if the user still has a valid session at the OP.

Given this, it looks like the check session is useful to know if the user logged out at the OP ASAP, without waiting for the next silent authorization request to be made.

Is this correct?

**Comment by brockallen** [comment]
Check session is used to know if/when the user's authentication status has changed. Once it has, then it's recommended that the client make a request with prompt=none to get a new id_token (and session state) without prompting the user. If that's not possible, then the user is really no longer logged in, and then the user must be prompted to login again.

**Comment by brockallen** [comment]
Are we all set on this PR/issue?

**Comment by mderriey** [comment]
Yes, I added the last part about session checking. It would be great if you could review it.

**Comment by brockallen** [comment]
Ok, only one comment. Rest looks good. Thanks.

**Comment by mderriey** [comment]
Thanks Brock, I reworded the part you mentioned.
Let me know if there's anything else.

**Comment by brockallen** [comment]
Good for now. I'll merge. Thanks!

**Pull request merged**
