### PR TITLE
Update JS walkthrough to use oidc-client-js

### PR DESCRIPTION
**Pull request by mderriey**
Hi,

Here's my first attempt at migrating the JS walkthrough to use [`oidc-client-js`](https://github.com/IdentityModel/oidc-client-js).

I linked to my personal repository where I keep the associated code. Please let me know if you want that somewhere else and I'll update the link.

As always, any comments/feedback would be much appreciated.

Thanks!

### CODE REVIEW

**Comment by mderriey** [comment]
Also, you can have a look at the page [here](https://mderriey.github.io/Documentation/docsv2/overview/jsGettingStarted.html)

**Comment by ranieuwe** [comment]
Looks good and well written. I would add instructions on setting up logging in the IdentityServer setup part. Probably something will go wrong and whoever follows the tutorial will be confused as to what went wrong.

**Comment by leastprivilege** [comment]
@brockallen looks good to you?

**Comment by brockallen** [comment]
Very nice. Thanks!

**Pull request merged**
