### PR TITLE
Fixes error in _login.html example code

### PR DESCRIPTION
**Pull request by MikaelBertze**

### CODE REVIEW

**Comment by brockallen** [comment]
Doesn't {{ render with something special in MD?

**Comment by MikaelBertze** [comment]
Not sure if I understand the question. The double curly braces should not be separated by a space when used as an Angular expression.

**Comment by brockallen** [comment]
Correct, but in markdown they don't display as "{{" when written that way -- unless you see that it's working correctly?

**Comment by MikaelBertze** [comment]
Looks good in my branch when viewed through github

image

**Comment by brockallen** [comment]
My recollection when I wrote it was that it wasn't displaying properly, but it's working now, then great. Thanks!

**Pull request merged**
