### PR TITLE
Updated the verbiage and code sample

### PR DESCRIPTION
**Pull request by amit-g**
Updated the verbiage and code sample to make it simple for the first
time reader

### CODE REVIEW

**Comment by leastprivilege** [comment]
I will never ever release docs or a sample with 

ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;

sorry.

**Comment by leastprivilege** [comment]
Fix your SSL.

**Comment by amit-g** [comment]
That line wasn't supposed to be in the documentation sample. I had to use that in my local test code as my mmc was crashing. I would remove it.

Sorry Dominick for wasting your time.

**Comment by brockallen** [comment]
I'd suggest to re-do the PR for the docs without that line. The rest was fine.

**Pull request closed without merging**
